name: Build Wheels

on:
  release:
    types: [published, edited]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        with:
          package-dir: .
          output-dir: dist
          config-file: "{package}/pyproject.toml"
      - uses: actions/upload-artifact@v4
        with:
          name: triangle-wheels-${{ matrix.os }}.zip
          path: dist/
      - name: Get upload_url for Release Assets
        id: get_upload_url
        run: |
          UPLOAD_URL=$(jq -r .release.upload_url "$GITHUB_EVENT_PATH")
          echo "::set-output name=upload_url::$UPLOAD_URL"
        shell: bash
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
          asset_path: dist/triangle-wheels-${{ matrix.os }}.zip
          asset_name: triangle-${{ matrix.os }}.zip
          asset_content_type: application/zip
      # - name: Publish to pypi
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_PASS }}
